
clear
clc

main2

%[x,fval,exitflag,output,lambda,grad,hessian] = fmincon(@myfunc, ...
%    [-9;-9], ...
%    zeros(2,2), zeros(2,1), ...
%    zeros(2,2), zeros(2,1), ...
%    [-10;-10], [10;-8])

%options = optimoptions('fmincon', 'Display', 'iter');
[x,fval,exitflag,output,lambda,grad,hessian] = fmincon(@myfunc, ...
    [-20;-30], ...
    zeros(2,2), zeros(2,1), ...
    zeros(2,2), zeros(2,1), ...
    [-40;-30], [-15;30])
%    'Display', 'iter')
%    options)

area = [-40 -30 ; ...
        -40 30 ; ...
        -15 30 ; ...
        -15 -30];


hold on
drawPolygon(area)
plot(x(1), x(2), 'r*')
hold off
